name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v1
        with:
          python-version: "3.13"

      - name: Sync dependencies
        run: uv sync

      - name: Run unit tests
        run: uv run --with pytest pytest

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v1
        with:
          python-version: "3.13"

      - name: Sync dependencies
        run: uv sync

      - name: Install just
        uses: extractions/setup-just@v1

      - name: Build standalone binary
        run: just build

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: vrdx-linux
          path: bin/vrdx
